# Setup
# site.st
title:               De-Note
tagline:             sparkafka's dev blog
description:         "Data Engineer"
url:                 "https://sparkafka.github.io"
baseurl:             "/de-note"
paginate:            5
permalink:           /:title/

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
