# Setup
title:               De-Note
tagline:             sparkafka's dev blog
description:         'sparkafka'
url:                 
baseurl:             'de-note'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
